name: Build

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test_and_build:
    strategy:
      fail-fast: false
      matrix:
        version:
          - stable
          - nightly
    name: Test and Build - ${{ matrix.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install ${{ matrix.version }}
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.version }}
          target: x86_64-unknown-linux-gnu
      - uses: Swatinem/rust-cache@v2
        with:
          cache-directories: ~/.cache/sccache
      - uses: mozilla-actions/sccache-action@v0.0.5
      - name: Setup sccache
        run: |
          echo "SCCACHE_GHA_ENABLED=true" >>$GITHUB_ENV
          echo "RUSTC_WRAPPER=sccache" >>$GITHUB_ENV
      - run: cargo test --workspace --no-fail-fast -- --nocapture
        timeout-minutes: 20
        env:
          RUST_BACKTRACE: "1"
          RUST_LOG: "debug"
      - run: cargo build --workspace --verbose
        timeout-minutes: 5
  lints:
    name: Clippy and Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install toolchain and components
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          components: rustfmt, clippy
      - run: cargo fmt -- --color=always --check
      - run: cargo check --tests --workspace --verbose
      - run: cargo clippy --workspace --verbose -- -D warnings
